services:
  - type: web
    name: twigane-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    disk:
      name: models-disk
      mountPath: /opt/render/project/src/models
      sizeGB: 2 